[package]
name = "dazeus-plugin-factoids-rs"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dazeus = "0.4.0"
docopt = "1.1.0"